version: "3"
services:
  server:
    build: .
    ports:
      - 80:80
    volumes:
      - .:/usr/var/app
    environment:
      - SESSION_SECRET=sfo34htoi4nrfnaewoig45
    command: rerun -p "**/*.{rb,ru}" --background "rackup -p 80 -o 0.0.0.0"
  test:
    build: .
    volumes:
      - ./tests:/usr/var/app/tests
      - ./classes:/usr/var/app/classes
    command: ruby ./tests/run.rb
